services:
  - type: web
    name: streak-project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./venv/bin/gunicorn streak_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
    plan: free