# render.yaml
services:
  - type: web
    name: streak-project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn streak_project.wsgi:application"
    env: python
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    plan: free